# Generated by Django 3.2.5 on 2022-06-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_listener_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedata',
            name='hash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
